version: "3.9"

services:
  # ---------- PostgreSQL Database ----------
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  # ---------- NestJS Backend ----------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs-backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: todo_db
      NODE_ENV: production
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - app-network

  # ---------- Angular Frontend ----------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - app-network

# ---------- Shared Volume ----------
volumes:
  pgdata:

# ---------- Shared Network ----------
networks:
  app-network:
    driver: bridge
